name: Build Jetson Image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: before image build
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: build the image
        run: docker buildx build --platform linux/arm64 -t "${{ secrets.DOCKER_USERNAME }}"/tfod-wkspc:latest-jetson --push ./dockerfiles/jetson/
